apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.10.0
    helm:
      values: |
        serviceAccount:
          name: grafana
        replicas: 2
        adminPassword: admin
        rbac:
          create: true
          rules:
            - apiGroups: [""]
              resources: ["pods", "secrets", "configmaps"]
              verbs: ["get", "list", "watch"]
        extraVolumes:
          - name: grafana-temp
            emptyDir: {}
        extraVolumeMounts:
          - name: grafana-temp
            mountPath: /tmp
        securityContext:
          runAsUser: 472
          fsGroup: 472
          runAsNonRoot: true
        containerSecurityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        grafana.ini:
          server:
            root_url: "http://localhost:30000"
          log:
            level: debug
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default