apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.10.0
    helm:
      values: |
        serviceAccount:
          name: grafana
        replicas: 2
        adminPassword: admin
        automountServiceAccountToken: false
        extraVolumes:
          - name: grafana-temp
            emptyDir: {}
        extraVolumeMounts:
          - name: grafana-temp
            mountPath: /tmp
        securityContext:
          runAsUser: 472
          fsGroup: 472
          runAsNonRoot: true
          fsGroup: 472
        containerSecurityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        grafana.ini:
          log:
            level: info
#        ingress:
#          enabled: true
#          hosts:
#            - "grafana.test.io"
#          ingressClassName: "nginx"
#        datasources:
#          datasources.yaml:
#            apiVersion: 1
#            datasources:
#            - name: Prometheus
#              type: prometheus
#              url: http://prometheus-server.prometheus.svc.cluster.local:9090
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default