apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.10.0
    helm:
      values: |
        serviceAccount:
          name: grafana
        replicas: 2
        adminPassword: admin
        rbac:
          create: true
          rules:
            - apiGroups: [""]
              resources: ["pods", "secrets", "configmaps"]
              verbs: ["get", "list", "watch"]
        extraVolumes:
          - name: grafana-temp
            emptyDir: {}
        extraVolumeMounts:
          - name: grafana-temp
            mountPath: /tmp
        containerSecurityContext:
          readOnlyRootFilesystem: true
        ingress:
          enabled: true
          hosts:
            - "grafana.local"
          ingressClassName: "nginx"
        grafana.ini:
          log:
            level: debug
          database:
            type: mysql
            host: my-mysql.default.svc.cluster.local:3306
            name: grafana
            user: root
            password: sWO84vfbws
            ssl_mode: disable
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default