apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
spec:
  source:
    chart: haproxy
    repoURL: https://haproxytech.github.io/helm-charts
    targetRevision: 1.24.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: haproxy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default