apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    helm:
      version: v3
      values: |
        fullnameOverride: "ingress-nginx"
        controller:
          image:
            readOnlyRootFilesystem: true
          extraVolumes:
          - name: empty-dir
            emptyDir: {}
          extraVolumeMounts:
          - mountPath: /etc/nginx
            name: empty-dir
            subPath: app-nginx-dir
          - mountPath: /etc/ingress-controller
            name: empty-dir
            subPath: app-controller-dir
          - mountPath: /tmp
            name: empty-dir
            subPath: tmp-dir
          - mountPath: /tmp/nginx
            name: empty-dir
            subPath: app-tmp-dir
          - mountPath: /etc/ingress-controller/telemetry
            name: empty-dir
            subPath: app-telemetry-dir
          extraInitContainers:
            - name: prepare-nginx-folder
              image: registry.k8s.io/ingress-nginx/controller:v1.11.3@sha256:d56f135b6462cfc476447cfe564b83a45e8bb7da2774963b00d12161112270b7
              command:
                - /bin/bash
              args:
                - -ec
                - |
                  #!/bin/bash
                  cp -r /etc/nginx/* /nginx
                  cp -r /etc/ingress-controller/* /ingress-controller
              volumeMounts:
                - name: empty-dir
                  mountPath: /nginx
                  subPath: app-nginx-dir
                - name: empty-dir
                  mountPath: /ingress-controller
                  subPath: app-controller-dir
          admissionWebhooks:
            certManager:
              enabled: true
          podAnnotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
          replicaCount: 2
          config:
            generate-request-id: "false"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default