apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default