apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-addons
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  source:
    path: istio-addons
    repoURL: git@github.com:KacperKafara/argocd.git
    targetRevision: istio
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-addons
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  project: default