apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  destination:
    namespace: mysql
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.3.1
    chart: bitnami/mysql
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true