apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-test
  namespace: argocd
spec:
  source:
    repoURL: git@github.com:KacperKafara/argocd.git
    targetRevision: test
    path: ingress-test
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true