application:
  name: canary-app
  host: canary.istio.com
  gateway: istio-system/microservice-gateway

prod:
  replicas: 2
  subnet: v1
  weight: 80
  image:
    repository: nginx
    tag: 1.28.0

canary:
  enabled: true
  subnet: v2
  replicas: 1
  weight: 20
  image:
    repository: nginx
    tag: 1.29.2
