apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
spec:
  secretName: ingress-cert
  commonName: "*.istio.com"
  duration: 8760h
  renewBefore: 720h
  subject:
    organizations:
      - Istio
  dnsNames:
    - "*.istio.com"
  issuerRef:
    name: ca-issuer
    kind: Issuer