apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: prometheus-cm
    options:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/part-of: prometheus
    files:
      - prometheus/prometheus.yaml
generatorOptions:
  disableNameSuffixHash: true