apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
spec:
  sources:
    - repoURL: https://github.com/KacperKafara/argocd.git
      targetRevision: victoria
      path: database
  project: infrastructure
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
      - CreateNamespace=true