apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  sources:
    - chart: fluent-bit
      repoURL: https://fluent.github.io/helm-charts
      targetRevision: 0.52.0
      helm:
        valueFiles:
          - $config/logging/fluent-bit/values.yaml
    - repoURL: https://github.com/KacperKafara/argocd.git
      targetRevision: main
      path: logging/fluent-bit
      ref: config
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: monitoring