apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/KacperKafara/argocd.git
    targetRevision: main
    path: microservices
    directory:
      recurse: true
  project: apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: microservices
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
      - CreateNamespace=true