apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/KacperKafara/argocd.git
    targetRevision: minimal
    path: operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: operator