apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role-cluster
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "list", "watch" ]

  - apiGroups: [ "istio.com" ]
    resources: [ "nginx" ]
    verbs: [ "list", "watch" ]
