apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginx.istio.com
spec:
  group: istio.com
  scope: Namespaced
  names:
    plural: nginx
    singular: nginx
    kind: Nginx
    shortNames:
      - ng
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                  description: "Host cannot be null"
              required:
                - host
            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
              properties:
                message:
                  type: string