{{- if .Values.canary.enabled | default false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.application.name }}-canary"
  labels:
    app: "{{ .Values.application.name }}-canary"
    name: "{{ .Values.application.name }}"
spec:
  replicas: {{ .Values.canary.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.application.name }}-canary"
  template:
    metadata:
      labels:
        app: "{{ .Values.application.name }}-canary"
        name: "{{ .Values.application.name }}"
    spec:
      containers:
        - name: "{{ .Values.application.name }}-canary"
          image: "{{ .Values.canary.image.repository }}:{{ .Values.canary.image.tag }}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
{{- end }}